In [1]:
import numpy as np
import pandas as pd

from sklearn.base import BaseEstimator
from sklearn.base import ClassifierMixin

from sklearn.model_selection import BaseCrossValidator

from sklearn.utils.validation import check_X_y, check_is_fitted
from sklearn.utils.validation import check_array
from sklearn.utils.multiclass import check_classification_targets
from sklearn.metrics.pairwise import pairwise_distances

### 1

In [12]:
X = np.array([[1, 2, 3]])
X_ = np.array([[1, 2, 2],
               [4, 5, 4],
               [10, 12, 13]])
point_dist = pairwise_distances(
                np.concatenate([X, X_], axis=0)
                )[0,:]
point_dist

array([ 0.        ,  1.        ,  4.35889894, 16.76305461])

In [13]:
y = np.array([1, 2, 3])
X_ = np.array([[4, 5, 4],
               [10, 12, 13],
               [1, 2, 2]])
X = np.array([[1, 2, 3]])
y_pred = np.zeros(X.shape[0])

#for i, item in enumerate(X):
# Caluclate the distance between item (new point)
# and the X_train (self.X_)
point_dist = pairwise_distances(
    np.concatenate([X, X_], axis=0)
    )[0, 1:]
# pairwise_distances gives the whole matrix of distances
# between all points, we just need distance between
# the newpoint and others
 

In [14]:
dist = np.argsort(point_dist)[:2]
dist

array([2, 0], dtype=int64)

In [17]:
labels = y[dist]
float(np.bincount(labels).argmax())

1.0

In [21]:
list(labels).count

<function list.count(value, /)>

In [22]:
max(set(list(labels) ), key=list(labels).count)

1

In [2]:
import sklearn_questions
from sklearn.utils.estimator_checks import check_estimator
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier

from sklearn_questions import KNearestNeighbors
from sklearn_questions import MonthlySplit

In [3]:
X, y = make_classification(n_samples=200, n_features=20,
                            random_state=42)
X_train, X_test, y_train, y_test = \
    train_test_split(X, y, random_state=42)


In [4]:
X_train.shape

(150, 20)

In [5]:
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
y_pred_sk = knn.fit(X_train, y_train).predict(X_test)


c:\Users\matis\anaconda3\envs\datacamp\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\matis\anaconda3\envs\datacamp\Lib\site-packages\joblib\externals\loky\backend\context.py", line 282, in _count_physical_cores
    raise ValueError(f"found {cpu_count_physical} physical cores < 1")


In [6]:
y_pred_sk

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0])

In [7]:
onn = KNearestNeighbors(k)
y_pred_me = onn.fit(X_train, y_train).predict(X_test)

In [9]:
y_pred_me == y_pred_sk

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [116]:
onn.X_

array([[-0.48530584,  0.56288086,  1.34147592, ...,  1.01146304,
        -1.05890759,  0.00369567],
       [-1.14826329, -1.12254481,  0.82973242, ..., -1.29958124,
        -0.54668008,  1.34046105],
       [ 0.45122532,  1.66722411,  0.83019181, ..., -0.77265945,
         0.22228986, -0.67699514],
       ...,
       [-0.58461773, -0.93650637,  0.4583867 , ..., -0.63730775,
        -0.8385858 ,  1.2289805 ],
       [ 0.49774309,  0.8389405 ,  1.79521136, ..., -0.32066763,
         0.60672306,  0.88765543],
       [-0.37283315,  0.22468473, -0.4374583 , ..., -0.88749218,
        -0.78489831,  0.41953244]])

In [ ]:
assert_array_equal(y_pred_me, y_pred_sk)

### 2

In [1]:
import numpy as np
import pandas as pd
from numpy.testing import assert_array_equal

from sklearn.utils.estimator_checks import check_estimator
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier

from sklearn_questions import KNearestNeighbors
from sklearn_questions import MonthlySplit

import sklearn_questions

In [2]:
end_date = '2021-01-31'
shuffle_data = True
date = pd.date_range(
        start='2020-01-01 00:00', end=end_date, freq='D'
    )
n_samples = len(date)
X = pd.DataFrame({'val': range(n_samples), 'date': date})
y = pd.DataFrame(
    np.array([i % 2 for i in range(n_samples)])
)

if shuffle_data:
    X, y = shuffle(X, y, random_state=0)

cv = MonthlySplit(time_col='date')

In [4]:
i=0
for train, test in cv.split(X, y):
    if i==0:
        print(f"train={list(train)}")
        print(type(train[0]))
        print(f"test={test}")
        print(f"X_train={X.iloc[list(train)].index}")
        print(f"X_test={X.iloc[test]}")
    i+=1

train=[12, 6, 1, 10, 26, 4, 15, 5, 7, 20, 14, 8, 21, 22, 17, 30, 29, 27, 2, 24, 18, 13, 16, 19, 3, 11, 23, 0, 28, 25, 9]
<class 'numpy.int32'>
test=[37 54 59 52 45 55 56 49 33 34 46 51 35 44 40 36 58 41 50 43 48 57 42 38
 53 31 32 39 47]
X_train=Index([100, 293, 132, 278, 340,  37, 173,  54,  60, 230, 345,  12, 308, 396,
       332, 259, 134, 368,  74, 331, 135,  59, 171, 255,  78, 311,  76,  65,
       341, 284, 361],
      dtype='int64')
X_test=     val       date
357  357 2020-12-23
10    10 2020-01-11
4      4 2020-01-05
223  223 2020-08-11
122  122 2020-05-02
26    26 2020-01-27
45    45 2020-02-15
142  142 2020-05-22
219  219 2020-08-07
176  176 2020-06-25
280  280 2020-10-07
141  141 2020-05-21
170  170 2020-06-19
358  358 2020-12-24
6      6 2020-01-07
175  175 2020-06-24
194  194 2020-07-13
1      1 2020-01-02
168  168 2020-06-17
320  320 2020-11-16
113  113 2020-04-23
374  374 2021-01-09
295  295 2020-10-22
301  301 2020-10-28
52    52 2020-02-22
319  319 2020-11-15
154  154 

In [8]:
X.index
type(train[0])

int

In [5]:
train=[12, 6, 1,
        10, 26, 4, 15, 5, 7, 20, 14, 8, 21, 
        22, 17, 30, 29, 27, 2, 24, 18, 13, 
        16, 19, 3, 11, 23, 0, 28, 25, 9]
X.iloc[train]

val       date
100  100 2020-04-10
293  293 2020-10-20
132  132 2020-05-12
278  278 2020-10-05
340  340 2020-12-06
37    37 2020-02-07
173  173 2020-06-22
54    54 2020-02-24
60    60 2020-03-01
230  230 2020-08-18
345  345 2020-12-11
12    12 2020-01-13
308  308 2020-11-04
396  396 2021-01-31
332  332 2020-11-28
259  259 2020-09-16
134  134 2020-05-14
368  368 2021-01-03
74    74 2020-03-15
331  331 2020-11-27
135  135 2020-05-15
59    59 2020-02-29
171  171 2020-06-20
255  255 2020-09-12
78    78 2020-03-19
311  311 2020-11-07
76    76 2020-03-17
65    65 2020-03-06
341  341 2020-12-07
284  284 2020-10-11
361  361 2020-12-27

In [15]:
X.loc[X.index == train]

ValueError: ('Lengths must match to compare', (397,), (31,))

In [19]:
X['idx_tmp'] = X.index
X.reset_index(inplace=True, drop=True)
X_tmp = X[X['idx_tmp'].isin(train)]
X.drop(columns=["idx_tmp"], inplace=True)
idx_train = X_tmp.index

In [24]:
train

[12,
 6,
 1,
 10,
 26,
 4,
 15,
 5,
 7,
 20,
 14,
 8,
 21,
 22,
 17,
 30,
 29,
 27,
 2,
 24,
 18,
 13,
 16,
 19,
 3,
 11,
 23,
 0,
 28,
 25,
 9]

In [25]:
X[X['idx_tmp']==pd.Series(train)]

ValueError: Can only compare identically-labeled Series objects

In [28]:
X[X['idx_tmp'].isin(train)]

index  val       date  idx_tmp
8       12   12 2020-01-13       12
40       6    6 2020-01-07        6
41       1    1 2020-01-02        1
54      10   10 2020-01-11       10
55      26   26 2020-01-27       26
59       4    4 2020-01-05        4
63      15   15 2020-01-16       15
66       5    5 2020-01-06        5
69       7    7 2020-01-08        7
72      20   20 2020-01-21       20
74      14   14 2020-01-15       14
91       8    8 2020-01-09        8
110     21   21 2020-01-22       21
123     22   22 2020-01-23       22
137     17   17 2020-01-18       17
140     30   30 2020-01-31       30
183     29   29 2020-01-30       29
190     27   27 2020-01-28       27
191      2    2 2020-01-03        2
208     24   24 2020-01-25       24
220     18   18 2020-01-19       18
226     13   13 2020-01-14       13
247     16   16 2020-01-17       16
260     19   19 2020-01-20       19
263      3    3 2020-01-04        3
275     11   11 2020-01-12       11
295     23   23 2020-01-24       23
297      0    0 2020-01-01        0
346     28   28 2020-01-29       28
372     25   25 2020-01-26       25
388      9    9 2020-01-10        9

In [9]:
train

[12,
 6,
 1,
 10,
 26,
 4,
 15,
 5,
 7,
 20,
 14,
 8,
 21,
 22,
 17,
 30,
 29,
 27,
 2,
 24,
 18,
 13,
 16,
 19,
 3,
 11,
 23,
 0,
 28,
 25,
 9]

In [17]:
list_months = X['date'].dt.to_period('M').unique()
sorted(list_months)

[Period('2020-01', 'M'),
 Period('2020-02', 'M'),
 Period('2020-03', 'M'),
 Period('2020-04', 'M'),
 Period('2020-05', 'M'),
 Period('2020-06', 'M'),
 Period('2020-07', 'M'),
 Period('2020-08', 'M'),
 Period('2020-09', 'M'),
 Period('2020-10', 'M'),
 Period('2020-11', 'M'),
 Period('2020-12', 'M'),
 Period('2021-01', 'M')]

In [28]:
date = pd.date_range(start='2020-01-01', end=end_date, freq='D')
n_samples = len(date)
X = pd.DataFrame(range(n_samples), index=date, columns=['val'])
y = pd.DataFrame(
    np.array([i % 2 for i in range(n_samples)]),
    index=date
)

if shuffle_data:
    X, y = shuffle(X, y, random_state=0)

X_1d = X['val']

cv = MonthlySplit()
cv_repr = "MonthlySplit(time_col='index')"

In [30]:
X_1d

2020-03-06     65
2020-05-12    132
2020-03-15     74
2020-03-19     78
2020-02-07     37
             ... 
2020-11-19    323
2020-07-11    192
2020-04-27    117
2020-02-17     47
2020-06-21    172
Name: val, Length: 397, dtype: int64

In [31]:
X

val
2020-03-06   65
2020-05-12  132
2020-03-15   74
2020-03-19   78
2020-02-07   37
...         ...
2020-11-19  323
2020-07-11  192
2020-04-27  117
2020-02-17   47
2020-06-21  172

[397 rows x 1 columns]

In [32]:
X.columns

Index(['val'], dtype='object')

In [34]:
X.index

DatetimeIndex(['2020-03-06', '2020-05-12', '2020-03-15', '2020-03-19',
               '2020-02-07', '2020-02-24', '2020-10-20', '2020-03-01',
               '2020-01-13', '2020-12-27',
               ...
               '2020-07-30', '2020-01-10', '2020-12-25', '2020-07-14',
               '2020-09-08', '2020-11-19', '2020-07-11', '2020-04-27',
               '2020-02-17', '2020-06-21'],
              dtype='datetime64[ns]', length=397, freq=None)

In [36]:
X.sort_index()

val
2020-01-01    0
2020-01-02    1
2020-01-03    2
2020-01-04    3
2020-01-05    4
...         ...
2021-01-27  392
2021-01-28  393
2021-01-29  394
2021-01-30  395
2021-01-31  396

[397 rows x 1 columns]

In [37]:
pd.DataFrame(X_1d)

val
2020-03-06   65
2020-05-12  132
2020-03-15   74
2020-03-19   78
2020-02-07   37
...         ...
2020-11-19  323
2020-07-11  192
2020-04-27  117
2020-02-17   47
2020-06-21  172

[397 rows x 1 columns]